name: Contexto
run-name: Estoy aprendiendo a usar contextos.
on: 
  push:
    branches: [main, aprendiendo-github-actions]
    
workflow_dispatch:

jobs:
  check:
    if: ${{ github.ref == 'refs/head/aprendiendo-github-actions' }}
    runs-om: ubuntu-latest
    steps:
      run: echo "Desplegando en la rama $GITHUB_REF"
