name: Triggers en GitHub
on:
  push:
    branches:
      - 'aprendiendo-github-actions'
  pull_request:
    branches:
      - 'aprendiendo-github-actions'
      - 'main'
  schedule:
    - cron: '25 * * * *'

jobs:
  usando-triggers:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: Correr script
        run: python hola-mundo.py
  
